services:
  wordpress:
    image: wordpress:latest
    container_name: wordpress-container
    environment:
      WORDPRESS_DB_HOST: "{{ rds_endpoint }}"  # Sustituyendo {{ rds_endpoint }} con la variable desde vars.yml
      WORDPRESS_DB_NAME: "{{ db_name }}"
      WORDPRESS_DB_USER: "{{ db_user }}"
      WORDPRESS_DB_PASSWORD: "{{ db_password }}"
    volumes:
      - ./wordpress:/var/www/html  # Carpeta local con los archivos de WordPress (si es necesario)
    ports:
      - "8080:80"
    restart: always
