apiVersion: v1
kind: Service
metadata:
  name: chat-app-agd-service
  namespace: default
spec:
  selector:
    app: chat-app-agd
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: LoadBalancer
