apiVersion: apps/v1
kind: Deployment
metadata:
  name: lgdv2
spec:
  replicas: 6  # Número de réplicas (3 con wget y 3 con ab)
  selector:
    matchLabels:
      app: load-generator
  template:
    metadata:
      labels:
        app: load-generator
    spec:
      containers:
      - name: load-generator
        image: httpd:alpine  # Usamos httpd:alpine, que contiene apache2-utils
        command:
          - /bin/sh
          - -c
          - |
              while true; do
                ab -n 10000000 -c 100000 http://a23ca4c965b334d70adc426a4739bd78-1276965498.eu-west-3.elb.amazonaws.com/
              done
            
